from enum import Enum

class SOPStatus(str, Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"

class SOPCategory(str, Enum):
    MANUFACTURING = "MANUFACTURING"
    SAFETY = "SAFETY"
    QUALITY = "QUALITY"
    MAINTENANCE = "MAINTENANCE"
    IT = "IT"
    AUTOMATION = "AUTOMATION"
    HR = "HR"
    ADMINISTRATION = "ADMINISTRATION"

class WorkflowRole(str, Enum):
    AUTHOR = "AUTHOR"
    TECHNICAL_REVIEWER = "TECHNICAL_REVIEWER"
    DEPARTMENT_MANAGER = "DEPARTMENT_MANAGER"
    QUALITY_APPROVAL = "QUALITY_APPROVAL"
    ADMINISTRATOR = "ADMINISTRATOR"
