from enum import Enum

class NodeType(str, Enum):
    INFORMATION = "INFORMATION"
    INTERACTIVE_LESSON = "INTERACTIVE_LESSON"
    VIDEO = "VIDEO"
    PDF = "PDF"
    QUIZ = "QUIZ"
    SIMULATION = "SIMULATION"
    PRACTICAL_TASK = "PRACTICAL_TASK"
    ASSESSMENT = "ASSESSMENT"
    CERTIFICATE = "CERTIFICATE"

class NodeStatus(str, Enum):
    LOCKED = "LOCKED"
    UNLOCKED = "UNLOCKED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"

class DependencyType(str, Enum):
    MANDATORY = "MANDATORY"
    OPTIONAL = "OPTIONAL"
    RECOMMENDED = "RECOMMENDED"
