import React from 'react';

export default function AssetPreviewModal({ asset, icon, onClose }) {
  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(0,0,0,0.8)', zIndex: 1000,
      display: 'flex', alignItems: 'center', justifyContent: 'center'
    }}>
      <div style={{
        background: '#1a1d24', width: '800px', height: '600px', borderRadius: '8px', 
        border: '1px solid #4a5568', display: 'flex', overflow: 'hidden'
      }}>
        
        {/* Preview Area */}
        <div style={{ flex: 1, background: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRight: '1px solid #2d3748' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: '120px' }}>{icon}</div>
            <p style={{ color: '#718096' }}>Preview Generated by ThumbnailEngine</p>
          </div>
        </div>

        {/* Metadata Panel */}
        <div style={{ width: '300px', padding: '24px', display: 'flex', flexDirection: 'column', overflowY: 'auto' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '24px' }}>
            <h3 style={{ color: '#fff', margin: 0, fontSize: '18px' }}>Asset Details</h3>
            <button onClick={onClose} style={{ background: 'transparent', border: 'none', color: '#a0aec0', cursor: 'pointer', fontSize: '20px' }}>×</button>
          </div>

          <h4 style={{ color: '#e2e8f0', margin: '0 0 8px 0', wordBreak: 'break-all' }}>{asset.filename}</h4>
          <p style={{ color: '#a0aec0', fontSize: '13px', margin: '0 0 24px 0' }}>Type: {asset.type} | Ver: 1.0</p>

          <div style={{ marginBottom: '24px' }}>
            <h5 style={{ color: '#a0aec0', margin: '0 0 8px 0', textTransform: 'uppercase', fontSize: '12px' }}>AI Generated Tags</h5>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
              {asset.tags.map(t => (
                <span key={t} style={{ background: '#2c7a7b', color: 'white', padding: '2px 8px', borderRadius: '4px', fontSize: '11px' }}>{t}</span>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: '24px' }}>
            <h5 style={{ color: '#a0aec0', margin: '0 0 8px 0', textTransform: 'uppercase', fontSize: '12px' }}>AI Extracted Keywords</h5>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
              {asset.ai_keywords.map(k => (
                <span key={k} style={{ background: '#2d3748', color: '#e2e8f0', padding: '2px 8px', borderRadius: '4px', fontSize: '11px' }}>{k}</span>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: '24px' }}>
            <h5 style={{ color: '#a0aec0', margin: '0 0 8px 0', textTransform: 'uppercase', fontSize: '12px' }}>Knowledge Graph Links</h5>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, fontSize: '13px', color: '#63b3ed' }}>
              <li style={{ cursor: 'pointer', padding: '4px 0' }}>🔗 Related Equipment</li>
              <li style={{ cursor: 'pointer', padding: '4px 0' }}>🔗 Originating Department</li>
              <li style={{ cursor: 'pointer', padding: '4px 0' }}>🔗 Maintenance SOP</li>
            </ul>
          </div>
          
          <div style={{ marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <button style={{ background: '#3182ce', color: 'white', padding: '10px', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Download Original</button>
            <button style={{ background: 'transparent', color: '#a0aec0', padding: '10px', border: '1px solid #4a5568', borderRadius: '4px', cursor: 'pointer' }}>View Version History</button>
          </div>
        </div>

      </div>
    </div>
  );
}
