from enum import Enum

class QuestionType(str, Enum):
    SINGLE_CHOICE = "SINGLE_CHOICE"
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE"
    TRUE_FALSE = "TRUE_FALSE"
    FILL_IN_BLANK = "FILL_IN_BLANK"
    MATCHING = "MATCHING"
    SEQUENCE = "SEQUENCE"
    IMAGE_HOTSPOT = "IMAGE_HOTSPOT"
    SCENARIO = "SCENARIO"
    CASE_STUDY = "CASE_STUDY"
    CHECKLIST = "CHECKLIST"
    PROCESS_FLOW = "PROCESS_FLOW"
    AI_ORAL = "AI_ORAL"
    PRACTICAL = "PRACTICAL"

class AssessmentStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    EVALUATED = "EVALUATED"

class DifficultyLevel(str, Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"
    EXPERT = "EXPERT"
