from enum import Enum

class ContentType(str, Enum):
    INTERACTIVE_LESSON = "INTERACTIVE_LESSON"
    PDF = "PDF"
    VIDEO = "VIDEO"
    IMAGE_GALLERY = "IMAGE_GALLERY"
    FLOW_DIAGRAM = "FLOW_DIAGRAM"
    EQUIPMENT_DIAGRAM = "EQUIPMENT_DIAGRAM"
    SIMULATION = "SIMULATION"
    QUIZ = "QUIZ"
    CASE_STUDY = "CASE_STUDY"
    CHECKLIST = "CHECKLIST"
    REFERENCE_MATERIAL = "REFERENCE_MATERIAL"
    EXTERNAL_LINK = "EXTERNAL_LINK"
    AI_CONVERSATION = "AI_CONVERSATION"
    ANIMATION = "ANIMATION"
    THREE_D_MODEL = "THREE_D_MODEL"
    AR_VR = "AR_VR"

class ContentStatus(str, Enum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"

class DifficultyLevel(str, Enum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"
    EXPERT = "EXPERT"

class OrganizationType(str, Enum):
    CATEGORY = "CATEGORY"
    TOPIC = "TOPIC"
    SUBTOPIC = "SUBTOPIC"
    COLLECTION = "COLLECTION"
    PLAYLIST = "PLAYLIST"
    LEARNING_PATH = "LEARNING_PATH"
    MANUFACTURING_STAGE = "MANUFACTURING_STAGE"
    DEPARTMENT_LIBRARY = "DEPARTMENT_LIBRARY"
    ROLE_LIBRARY = "ROLE_LIBRARY"

class RelationshipType(str, Enum):
    PREREQUISITE = "PREREQUISITE"
    RELATED = "RELATED"
    DEPENDENCY = "DEPENDENCY"
    NEXT_STEP = "NEXT_STEP"
