"""
Task Engine for Enterprise Workflow (EP-07).
Manages enterprise tasks generated by workflow states.
"""
import logging
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from database.models import DbWorkflowTask, DbWorkflowAuditLog
from .models import WorkflowTaskModel

logger = logging.getLogger("WorkflowEngine.TaskEngine")


class TaskManagementService:
    def __init__(self, session_factory):
        self.session_factory = session_factory

    async def create_task(self, instance_id: str, title: str, owner_id: str, department_id: Optional[str] = None) -> WorkflowTaskModel:
        async with self.session_factory() as db:
            db_task = DbWorkflowTask(
                instance_id=instance_id,
                title=title,
                owner_id=owner_id,
                department_id=department_id,
                status="PENDING"
            )
            db.add(db_task)
            
            audit = DbWorkflowAuditLog(
                instance_id=instance_id,
                action_type="TASK_CREATED",
                actor_id="SYSTEM",
                details={"task_title": title, "owner": owner_id}
            )
            db.add(audit)
            
            await db.commit()
            await db.refresh(db_task)
            logger.info(f"Created task {db_task.id} for instance {instance_id}")
            return self._to_pydantic(db_task)

    async def complete_task(self, task_id: str, actor_id: str) -> WorkflowTaskModel:
        async with self.session_factory() as db:
            stmt = select(DbWorkflowTask).where(DbWorkflowTask.id == task_id)
            db_task = (await db.execute(stmt)).scalar_one_or_none()
            if not db_task:
                raise ValueError("Task not found.")
                
            db_task.status = "COMPLETED"
            db_task.completed_by = actor_id
            
            audit = DbWorkflowAuditLog(
                instance_id=db_task.instance_id,
                action_type="TASK_COMPLETED",
                actor_id=actor_id,
                details={"task_id": task_id}
            )
            db.add(audit)
            
            await db.commit()
            await db.refresh(db_task)
            return self._to_pydantic(db_task)

    def _to_pydantic(self, db_obj: DbWorkflowTask) -> WorkflowTaskModel:
        return WorkflowTaskModel(
            id=db_obj.id,
            instance_id=db_obj.instance_id,
            title=db_obj.title,
            description=db_obj.description,
            status=db_obj.status,
            owner_id=db_obj.owner_id,
            department_id=db_obj.department_id,
            due_date=db_obj.due_date,
            priority=db_obj.priority
        )
