from enum import Enum

class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    LOCKED = "LOCKED"
    SUSPENDED = "SUSPENDED"
    EXPIRED = "EXPIRED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    PASSWORD_RESET_REQUIRED = "PASSWORD_RESET_REQUIRED"
    SAP_CONTROLLED = "SAP_CONTROLLED"
