from enum import Enum

class RoleType(str, Enum):
    ADMINISTRATOR = "ADMINISTRATOR"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    MANAGER = "MANAGER"
    ASSISTANT_MANAGER = "ASSISTANT_MANAGER"
    SENIOR_ENGINEER = "SENIOR_ENGINEER"
    ENGINEER = "ENGINEER"
    EXECUTIVE_ENGINEER = "EXECUTIVE_ENGINEER"
    EXECUTIVE = "EXECUTIVE"
    SUPERVISOR = "SUPERVISOR"
    OPERATOR = "OPERATOR"
    INTERN = "INTERN"
    APPRENTICE = "APPRENTICE"
    VISITOR = "VISITOR"

class DepartmentType(str, Enum):
    AUTOMATION = "AUTOMATION"
    IT = "IT"
    PRODUCTION = "PRODUCTION"
    QUALITY = "QUALITY"
    MAINTENANCE = "MAINTENANCE"
    ELECTRICAL = "ELECTRICAL"
    MECHANICAL = "MECHANICAL"
    ROLLING_MILL = "ROLLING_MILL"
    STEEL_MELTING_SHOP = "STEEL_MELTING_SHOP"
    HR = "HR"
    SAFETY = "SAFETY"
    FINANCE = "FINANCE"
    STORES = "STORES"
    PURCHASE = "PURCHASE"
    SALES = "SALES"
    ADMINISTRATION = "ADMINISTRATION"

class VisibilityLevel(str, Enum):
    VISIBLE = "VISIBLE"
    HIDDEN = "HIDDEN"
    READ_ONLY = "READ_ONLY"
    EDITABLE = "EDITABLE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"

class AnnouncementType(str, Enum):
    ORGANIZATION = "ORGANIZATION"
    DEPARTMENT = "DEPARTMENT"
    MANAGER = "MANAGER"
    LEARNING = "LEARNING"
    MAINTENANCE = "MAINTENANCE"
