from enum import Enum

class AITaskType(str, Enum):
    QUESTION_ANSWERING = "QUESTION_ANSWERING"
    LESSON_EXPLANATION = "LESSON_EXPLANATION"
    MANUFACTURING_EXPLANATION = "MANUFACTURING_EXPLANATION"
    EQUIPMENT_EXPLANATION = "EQUIPMENT_EXPLANATION"
    SOP_EXPLANATION = "SOP_EXPLANATION"
    SAFETY_GUIDANCE = "SAFETY_GUIDANCE"
    ASSESSMENT_HELP = "ASSESSMENT_HELP"
    DASHBOARD_INSIGHTS = "DASHBOARD_INSIGHTS"

class AIPersona(str, Enum):
    GENERAL_ASSISTANT = "GENERAL_ASSISTANT"
    MANUFACTURING_EXPERT = "MANUFACTURING_EXPERT"
    SAFETY_EXPERT = "SAFETY_EXPERT"
    QUALITY_EXPERT = "QUALITY_EXPERT"
    MAINTENANCE_EXPERT = "MAINTENANCE_EXPERT"
    AUTOMATION_EXPERT = "AUTOMATION_EXPERT"
    SAP_GUIDE = "SAP_GUIDE"
    LEARNING_MENTOR = "LEARNING_MENTOR"
    ADMINISTRATOR_ASSISTANT = "ADMINISTRATOR_ASSISTANT"
