from enum import Enum

class CompetencyArea(str, Enum):
    MANUFACTURING_KNOWLEDGE = "MANUFACTURING_KNOWLEDGE"
    SAFETY_AWARENESS = "SAFETY_AWARENESS"
    QUALITY_UNDERSTANDING = "QUALITY_UNDERSTANDING"
    EQUIPMENT_KNOWLEDGE = "EQUIPMENT_KNOWLEDGE"
    DEPARTMENT_READINESS = "DEPARTMENT_READINESS"
    PROBLEM_SOLVING = "PROBLEM_SOLVING"
    DECISION_MAKING = "DECISION_MAKING"
    LEARNING_PROGRESS = "LEARNING_PROGRESS"
