from enum import Enum

class EmployeeStatus(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    PENDING_ONBOARDING = "PENDING_ONBOARDING"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    LOCKED = "LOCKED"
    ON_LEAVE = "ON_LEAVE"
    SUSPENDED = "SUSPENDED"
    TRANSFERRED = "TRANSFERRED"
    EXITED = "EXITED"
    TERMINATED = "TERMINATED"
    ARCHIVED = "ARCHIVED"
