from enum import Enum

class DepartmentType(str, Enum):
    AUTOMATION = "AUTOMATION"
    INFORMATION_TECHNOLOGY = "INFORMATION_TECHNOLOGY"
    STEEL_MELTING_SHOP = "STEEL_MELTING_SHOP"
    HOT_ROLLING_MILL = "HOT_ROLLING_MILL"
    COLD_ROLLING_MILL = "COLD_ROLLING_MILL"
    QUALITY_ASSURANCE = "QUALITY_ASSURANCE"
    MAINTENANCE = "MAINTENANCE"
    MECHANICAL = "MECHANICAL"
    ELECTRICAL = "ELECTRICAL"
    HUMAN_RESOURCES = "HUMAN_RESOURCES"
    PURCHASE = "PURCHASE"
    STORES = "STORES"
    SALES = "SALES"
    FINANCE = "FINANCE"
    ADMINISTRATION = "ADMINISTRATION"
    SAFETY = "SAFETY"
