from enum import Enum

class ContentType(str, Enum):
    LESSON = "LESSON"
    KNOWLEDGE_OBJECT = "KNOWLEDGE_OBJECT"
    PDF = "PDF"
    WORD_DOCUMENT = "WORD_DOCUMENT"
    POWERPOINT = "POWERPOINT"
    EXCEL = "EXCEL"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    MANUFACTURING_DIAGRAM = "MANUFACTURING_DIAGRAM"
    FLOWCHART = "FLOWCHART"
    EQUIPMENT_MANUAL = "EQUIPMENT_MANUAL"
    SOP = "SOP"
    SAFETY_MANUAL = "SAFETY_MANUAL"
    QUALITY_DOCUMENT = "QUALITY_DOCUMENT"
    ASSESSMENT = "ASSESSMENT"
    CERTIFICATE_TEMPLATE = "CERTIFICATE_TEMPLATE"

class CollectionType(str, Enum):
    PLAYLIST = "PLAYLIST"
    LEARNING_PATH = "LEARNING_PATH"
    ROLE_LIBRARY = "ROLE_LIBRARY"
    DEPARTMENT_LIBRARY = "DEPARTMENT_LIBRARY"
