from enum import Enum

class EmergencyType(str, Enum):
    FIRE = "FIRE"
    CHEMICAL_SPILL = "CHEMICAL_SPILL"
    ELECTRICAL_ACCIDENT = "ELECTRICAL_ACCIDENT"
    MEDICAL = "MEDICAL"
    EVACUATION = "EVACUATION"
    EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE"
