from enum import Enum

class AchievementType(str, Enum):
    LEARNING_MILESTONE = "LEARNING_MILESTONE"
    DEPARTMENT_MILESTONE = "DEPARTMENT_MILESTONE"
    MANUFACTURING_JOURNEY = "MANUFACTURING_JOURNEY"
    ASSESSMENT_ACHIEVEMENT = "ASSESSMENT_ACHIEVEMENT"
    SAFETY_ACHIEVEMENT = "SAFETY_ACHIEVEMENT"
    KNOWLEDGE_ACHIEVEMENT = "KNOWLEDGE_ACHIEVEMENT"
    PERFECT_SCORE = "PERFECT_SCORE"
    FAST_LEARNER = "FAST_LEARNER"
    AI_CHALLENGE = "AI_CHALLENGE"
