import React from 'react';
import { Link } from 'react-router-dom';
import BreadcrumbEngine from '../breadcrumbs/BreadcrumbEngine';

export default function SmartEntityPage({ profile }) {
  if (!profile) return <div>Loading Profile...</div>;

  const { entity, breadcrumbs, related_objects, recommendations } = profile;

  const renderSection = (title, items, icon) => {
    if (!items || items.length === 0) return null;
    return (
      <div style={{ marginBottom: '32px' }}>
        <h3 style={{ color: '#e2e8f0', borderBottom: '1px solid #2d3748', paddingBottom: '8px', marginBottom: '16px' }}>
          {icon} {title}
        </h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: '16px' }}>
          {items.map(item => (
            <Link 
              key={item.id} 
              to={`/studio/explore/${item.id}`}
              style={{ 
                background: '#1a1d24', border: '1px solid #2d3748', borderRadius: '8px', 
                padding: '16px', textDecoration: 'none', color: 'inherit',
                display: 'block', transition: 'all 0.2s',
                boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = '#63b3ed'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = '#2d3748'; e.currentTarget.style.transform = 'none'; }}
            >
              <h4 style={{ color: '#fff', margin: '0 0 4px 0' }}>{item.name}</h4>
              <p style={{ color: '#a0aec0', fontSize: '12px', margin: 0 }}>
                {item.type.replace('_', ' ')} • {item.relationship}
              </p>
            </Link>
          ))}
        </div>
      </div>
    );
  };

  return (
    <div style={{ flex: 1, overflowY: 'auto', padding: '24px' }}>
      <BreadcrumbEngine breadcrumbs={breadcrumbs} />
      
      <header style={{ marginBottom: '32px', background: 'linear-gradient(to right, #2c5282, #1a365d)', padding: '32px', borderRadius: '12px', color: 'white' }}>
        <span style={{ background: 'rgba(255,255,255,0.2)', padding: '4px 12px', borderRadius: '16px', fontSize: '12px', textTransform: 'uppercase', letterSpacing: '1px' }}>
          {entity.type.replace('_', ' ')}
        </span>
        <h1 style={{ fontSize: '48px', margin: '16px 0 8px 0', letterSpacing: '-1px' }}>{entity.name}</h1>
        <p style={{ color: '#bee3f8', margin: 0, fontSize: '16px', maxWidth: '600px' }}>
          {entity.attributes?.description || 'Enterprise entity profile dynamically generated by the Discovery Engine.'}
        </p>
      </header>

      <div style={{ display: 'flex', gap: '32px' }}>
        {/* Main Content Area */}
        <div style={{ flex: 3 }}>
          {renderSection("Parent Structure", related_objects.parents, "🏛️")}
          {renderSection("Child Structure", related_objects.children, "🔗")}
          {renderSection("Required Equipment", related_objects.equipment, "⚙️")}
          {renderSection("Standard Operating Procedures", related_objects.sops, "📄")}
          {renderSection("Required Training", related_objects.lessons, "🎓")}
          {renderSection("Other Relationships", related_objects.other, "🔹")}
        </div>

        {/* Right Sidebar (Recommendations) */}
        <div style={{ flex: 1 }}>
          <div style={{ background: '#1a1d24', border: '1px solid #2d3748', borderRadius: '8px', padding: '20px', position: 'sticky', top: '24px' }}>
            <h3 style={{ color: '#fff', margin: '0 0 16px 0', fontSize: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              ✨ AI Recommendations
            </h3>
            {recommendations.map(rec => (
              <div key={rec.id} style={{ padding: '12px', background: '#2d3748', borderRadius: '6px', marginBottom: '8px', cursor: 'pointer' }}>
                <h5 style={{ color: '#e2e8f0', margin: '0 0 4px 0', fontSize: '13px' }}>{rec.name}</h5>
                <p style={{ color: '#a0aec0', fontSize: '11px', margin: 0 }}>Recommended {rec.type}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
