from enum import Enum

class ResourceType(str, Enum):
    PDF = "PDF"
    WORD_DOCUMENT = "WORD_DOCUMENT"
    POWERPOINT = "POWERPOINT"
    VIDEO = "VIDEO"
    IMAGE = "IMAGE"
    EQUIPMENT_MANUAL = "EQUIPMENT_MANUAL"
    SOP = "SOP"
    SAFETY_DOCUMENT = "SAFETY_DOCUMENT"
    QUALITY_DOCUMENT = "QUALITY_DOCUMENT"
    ENGINEERING_DRAWING = "ENGINEERING_DRAWING"
    CHECKLIST = "CHECKLIST"
    REFERENCE_GUIDE = "REFERENCE_GUIDE"
    FUTURE_CAD = "FUTURE_CAD"
