from enum import Enum

class WidgetType(str, Enum):
    WELCOME_CARD = "WELCOME_CARD"
    LEARNING_PROGRESS = "LEARNING_PROGRESS"
    CURRENT_ROADMAP = "CURRENT_ROADMAP"
    TODAYS_TASKS = "TODAYS_TASKS"
    UPCOMING_ASSESSMENTS = "UPCOMING_ASSESSMENTS"
    ACHIEVEMENTS = "ACHIEVEMENTS"
    CERTIFICATES = "CERTIFICATES"
    NOTIFICATIONS = "NOTIFICATIONS"
    QUICK_ACTIONS = "QUICK_ACTIONS"
    DEPARTMENT_OVERVIEW = "DEPARTMENT_OVERVIEW"
    RECENT_ACTIVITY = "RECENT_ACTIVITY"
    LEARNING_STATISTICS = "LEARNING_STATISTICS"
    MANUFACTURING_JOURNEY = "MANUFACTURING_JOURNEY"
    AI_ASSISTANT = "AI_ASSISTANT"
    SAP_SUMMARY = "SAP_SUMMARY"

class WidgetSize(str, Enum):
    SMALL = "SMALL"       # 1x1 grid unit
    MEDIUM = "MEDIUM"     # 2x1 grid unit
    LARGE = "LARGE"       # 2x2 grid unit
    FULL_WIDTH = "FULL_WIDTH" # 4xN grid unit
