"""workflow_engine

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-29 06:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_workflow_name_version')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('target_entity_id', sa.String(length=128), nullable=True),
    sa.Column('target_entity_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_state', sa.String(length=128), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_tasks',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_approvals',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approver_id', sa.String(length=128), nullable=True),
    sa.Column('approver_department', sa.String(length=128), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_audit_logs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=128), nullable=True),
    sa.Column('to_state', sa.String(length=128), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_audit_logs')
    op.drop_table('workflow_approvals')
    op.drop_table('workflow_tasks')
    op.drop_table('workflow_instances')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
