from enum import Enum

class SafetyCategory(str, Enum):
    GENERAL = "GENERAL"
    FIRE = "FIRE"
    ELECTRICAL = "ELECTRICAL"
    MECHANICAL = "MECHANICAL"
    CHEMICAL = "CHEMICAL"
    HOT_WORK = "HOT_WORK"
    WORKING_AT_HEIGHT = "WORKING_AT_HEIGHT"
    CONFINED_SPACE = "CONFINED_SPACE"
    MACHINE = "MACHINE"
    MATERIAL_HANDLING = "MATERIAL_HANDLING"
    ENVIRONMENTAL = "ENVIRONMENTAL"
    CYBER_SECURITY = "CYBER_SECURITY"
    DEPARTMENT_SPECIFIC = "DEPARTMENT_SPECIFIC"

class HazardLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class PPEType(str, Enum):
    HELMET = "HELMET"
    SHOES = "SHOES"
    GLOVES = "GLOVES"
    GOGGLES = "GOGGLES"
    FACE_SHIELD = "FACE_SHIELD"
    EAR_PROTECTION = "EAR_PROTECTION"
    RESPIRATOR = "RESPIRATOR"
    CLOTHING = "CLOTHING"
    HARNESS = "HARNESS"
    DEPARTMENT_SPECIFIC = "DEPARTMENT_SPECIFIC"
